requirejs.config({
    paths:{
        jquery:"jquery-1.11.2"
    }
});
require(["jquery","play"],function($,play){
    setTimeout(function(){
        play();
        setInterval(function(){
            play();
        },2800);
},1400);
});